#!/bin/bash

set -ex

ANON_ROOT=${ANON_ROOT:-/var/ftp}
MAX_PORT=${MAX_PORT:-21100}
MIN_PORT=${MIN_PORT:-21110}
MAX_PER_IP=${MAX_PER_IP:-2}
MAX_LOGIN_FAILS=${MAX_LOGIN_FAILS:-2}
MAX_CLIENTS=${MAX_CLIENTS:-50}
MAX_RATE=${MAX_RATE:-6250000}
FTPD_BANNER=${FTPD_BANNER:-"banner"}

mkdir -p /var/run/vsftpd/empty

[ -f /etc/vsftpd.conf ] || cat <<EOF > /etc/vsftpd.conf
anon_max_rate=${MAX_RATE}
anon_upload_enable=YES
anon_root=${ANON_ROOT}
anonymous_enable=YES
background=NO
connect_from_port_20=YES
dirmessage_enable=YES
ftp_data_port=20
ftpd_banner=${FTPD_BANNER}
guest_enable=YES
hide_ids=YES
listen=YES
log_ftp_protocol=YES
max_clients=${MAX_CLIENTS}
max_login_fails=${MAX_LOGIN_FAILS}
max_per_ip=${MAX_PER_IP}
pasv_max_port=${MAX_PORT}
pasv_min_port=${MIN_PORT}
pasv_enable=YES
pasv_address=${PASSIVE_IP}
port_enable=YES
seccomp_sandbox=NO
#secure_chroot_dir=/var/run/vsftpd/empty
use_localtime=YES
write_enable=YES
xferlog_std_format=NO
xferlog_file=/dev/stdout
EOF

/usr/sbin/vsftpd "$@"
